services:
  loumo_main:
    container_name: loumo_main
    build:
      context: ./loumo-main
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3001:3000"
    networks:
      - caddy-network

networks:
  caddy-network:
    driver: bridge
    attachable: true
# correct deployment on sidiki vps
